In [3]:
import numpy as np
import os
import cv2
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Dense, Dropout, Flatten
from sklearn.model_selection import train_test_split

# from google.colab import drive
# drive.mount('/content/drive')
# Jupiter Notebook ist wirklich sehr praktisch

In [5]:
path = "C:/Users/DanielWeller/Meine Ablage/Colab Notebooks/UTKFace"

images = []
age = []

for img in os.listdir(path):
    print(img)
    ages = img.split("_")[0]
    img = cv2.imread(str(path)+"/"+str(img))
    print(img)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    images.append(np.array(img))
    age.append(np.array(ages))

age = np.array(age, dtype=np.int64)
images = np.array(images)


x_train_age, x_test_age, y_train_age, y_test_age = train_test_split(
images, age, random_state=42)

100_0_0_20170112213500903.jpg.chip.jpg
[[[201 206 215]
  [199 204 213]
  [198 203 212]
  ...
  [100  94  89]
  [105  94  90]
  [108  97  93]]

 [[199 204 213]
  [197 202 211]
  [200 205 214]
  ...
  [101  95  90]
  [106  95  91]
  [109  98  94]]

 [[197 202 211]
  [192 197 206]
  [196 201 210]
  ...
  [102  95  92]
  [107  95  93]
  [111  99  97]]

 ...

 [[242 236 237]
  [242 236 237]
  [241 235 236]
  ...
  [100  94  95]
  [100  94  95]
  [101  95  96]]

 [[241 235 236]
  [241 235 236]
  [239 233 234]
  ...
  [100  94  95]
  [100  94  95]
  [101  95  96]]

 [[241 235 236]
  [239 233 234]
  [237 231 232]
  ...
  [100  94  95]
  [100  94  95]
  [101  95  96]]]
100_0_0_20170112215240346.jpg.chip.jpg
[[[133 122 118]
  [135 124 120]
  [137 126 122]
  ...
  [162 158 153]
  [163 159 154]
  [163 159 154]]

 [[134 123 119]
  [136 125 121]
  [137 126 122]
  ...
  [162 158 153]
  [163 159 154]
  [163 159 154]]

 [[136 125 121]
  [136 125 121]
  [136 125 121]
  ...
  [162 158 153]
  [163 159 154

KeyboardInterrupt: 

In [ ]:
# Definiert Model
age_model = Sequential([

    #size=3 -> 3X3 Matrix
    
    #Output ist 198 in beispiel
    Conv2D(128, kernel_size=3, activation='relu', input_shape=(200, 200, 3)),

    # Es gibt keine Tensoren, pool=size =3 -> 3x3x1 dann bestimmen größte Zahl in Block
    # danach schrittweite 2 (strides) komplett erste schicht durch, danach 128 weitere Schichten (vorgabe von vorherigen Layer)
    MaxPool2D(pool_size=3, strides=2),

    #identisch wie erster
    Conv2D(128, kernel_size=3, activation='relu'),

    MaxPool2D(pool_size=3, strides=2),

    Conv2D(256, kernel_size=3, activation='relu'),

    MaxPool2D(pool_size=3, strides=2),

    Conv2D (512, kernel_size=3, activation='relu'),

    MaxPool2D(pool_size=3, strides=2),

    # Als Input 9x9x512 Matrix wird als Kette gebildet.
    Flatten(),

    # Überanpassung soll vermieden werden. Bei jedem Durchlauf (Batch?) werden 50% (0,5) der Verbindungen ausgeblendet
    Dropout(0.5),

    #Versteckte Schicht (Hidden layer) Zielvorgabe 512
    Dense(512, activation='relu'),

    #Versteckte Schicht (Hidden layer) Zielvorgabe 1
    Dense(1, activation='linear', name='age')
])

age_model.compile(
optimizer='adam',
loss='mse',
metrics =['mse']
)

In [ ]:
# Gibt eine Übersicht des Modells aus
print(age_model.summary ())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 198, 198, 128)     3584      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 98, 98, 128)      0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 96, 96, 128)       147584    
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 47, 47, 128)      0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 45, 45, 256)       295168    
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 22, 22, 256)      0

In [ ]:
# Training des Modells 2
training_age = age_model.fit(
x_train_age, y_train_age, batch_size=64, epochs=1)

Epoch 1/15
180/180 [==============================] - 4382s 24s/step - loss: 183297.2188 - mse: 183297.2188
Epoch 2/15
180/180 [==============================] - 4350s 24s/step - loss: 82.6286 - mse: 82.6286
Epoch 3/15
180/180 [==============================] - 4389s 24s/step - loss: 71.9045 - mse: 71.9045
Epoch 4/15
180/180 [==============================] - 4406s 24s/step - loss: 67.8368 - mse: 67.8368
Epoch 5/15
180/180 [==============================] - 4449s 25s/step - loss: 62.1930 - mse: 62.1930
Epoch 6/15
180/180 [==============================] - 4461s 25s/step - loss: 60.4510 - mse: 60.4510
Epoch 7/15
180/180 [==============================] - 4308s 24s/step - loss: 57.9543 - mse: 57.9543
Epoch 8/15
180/180 [==============================] - 4423s 25s/step - loss: 56.8138 - mse: 56.8138
Epoch 9/15
180/180 [==============================] - 4294s 24s/step - loss: 54.2470 - mse: 54.2470
Epoch 10/15
 54/180 [========>.....................] - ETA: 50:13 - loss: 53.1122 - mse: 53.

In [ ]:
# Evaluation des Models
test_age = age_model.evaluate(x_test_age, y_test_age)

NameError: ignored